theme: jekyll-theme-minimal

author:
  name: "Antoine Bourgois"
  github: "antoine-bourgois"
  linkedin: "https://www.linkedin.com/in/antoine-bourgois/"
  twitter: "https://x.com/Antoine_Brgs"

nav:
  - title: "Home"
    url: /

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
